environment:
    global:
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"
    matrix:
      - PYTHON: "C:\\Python26"
      - PYTHON: "C:\\Python27"
      - PYTHON: "C:\\Python34"
      - PYTHON: "C:\\Python35"

install: "%CMD_IN_ENV% %PYTHON%/Scripts/pip.exe install -r requirements.txt -r requirements-dev.txt"
before_test: "%CMD_IN_ENV% %PYTHON%/python.exe setup.py develop"
test_script: "%CMD_IN_ENV% %PYTHON%/Scripts/mamba.exe --enable-coverage"
after_test: "%CMD_IN_ENV% %PYTHON%/Scripts/coverage.exe report"
